### ISSUE TITLE
Sari Dis

### ISSUE THREAD

**Issue by erhansa68** [irgroup-classrooms/dis08-2021#24]
Erhan Sari
DIS20

**Comment by phschaer** [comment]
Ich verstehe leider nicht, was Sie mir mit diesem Ticket sagen wollen? Ihre Matrikelnummer ist in den Classrooms bereits hinterlegt, wenn es das sein sollte.

**Comment by erhansa68** [comment]
Sorry hab meine Matrikelnummer übersehen. Danke für Ihre Hilfe.
