### ISSUE TITLE
can't find my student id

### ISSUE THREAD

**Issue by luucafrank** [irgroup-classrooms/dis08-2021#32]
Hallo Herr phschaer, 

ich kann leider meine Student ID nicht im Classroom DIS08-2021 finden.

Nachname: Gillich
Studiengang: Data and Information Science 20
Fach: DIS08.1

Mit freundlichen Grüßen, 
Gillich

**Comment by phschaer** [comment]
Lieber Herr Gillich,

Ihre Matrikelnummer ist noch nicht vergeben und ich in der Liste eingetragen. Bitte nochmal genau nachsehen.

Alles Gute

Philipp Schaer

**Comment by luucafrank** [comment]
Hallo Herr Schaer, 

vielen lieben Dank für die umgehende Antwort. 

Jetzt hat alles geklappt.

Mit freundlichen Grüßen, 
Gillich
