### ISSUE TITLE
Gruppenzuteilung

### ISSUE THREAD

**Issue by michellecolic1** [irgroup-classrooms/dis08-2021#50]
Ich würde gerne in die Gruppe zwei gehen. Doch das geht leider nicht, weil die Studenten doppelt drin stehen

**Comment by phschaer** [comment]
Liebe Frau Colic, welches Team meinen Sie? Es gibt "Group 2", dort sind aber aktuell nur zwei Personen gelistet und keine Dopplungen. Die beiden Personen dort sind esraxak1 und JaninaSophieJanssen.

**Comment by phschaer** [comment]
Ich habe Sie jetzt mal proforma dem besagten Team hinzugefügt. Da ist noch irgendwo der Wurm drin, denn inzwischen sehe ich die Kommilitoninnen ebenfalls als doppelte Einträge. Geben Sie kurz Feedback, ob es nun das richtige Team war.

**Comment by michellecolic1** [comment]
Ja genau das ist die richtige Gruppe.

Vielen Dank

**Comment by Maurice1611** [comment]
Ich habe auch das Problem und kann meiner Gruppe nicht beitreten. Könnten Sie mich der Gruppe Data Noobs hinzufügen?

**Comment by phschaer** [comment]
Okay, habe Sie hinzugefügt.
