### ISSUE TITLE
Group join unable

### ISSUE THREAD

**Issue by Wanille** [irgroup-classrooms/dis08-2021#59]
Our group 'Notificationgang' is full even though theirs only two people in.
The two who haven't been able to join are: "Pexem" and "Luucafrank".

**Comment by luucafrank** [comment]
Unfortunately, we could not join the group 'Notificationgang'.

**Comment by phschaer** [comment]
solved - I just added you to this group.

**Comment by luucafrank** [comment]
Thanks for solving!
