### ISSUE TITLE
Classroom Assignements führt zu 404

### ISSUE THREAD

**Issue by marnemann** [irgroup-classrooms/dis08-2021#6]
Sehr geehrter Herr Schaer,

ich bin zwar dem Github Classroom beigetreten, wenn ich jedoch den Assignment Link öffne, wirft dieser einen 404 Fehler. Gibt es dafür eine Lösung?

Mit freundlichen Grüßen

Marc Arnemann

**Comment by phschaer** [comment]
Lieber Herr Arnemann,

das kann schonmal vorkommen, dass GitHub Classrooms im Hintergrund etwas "zickt". Einfach nochmal probieren. 

BTW: Matrikelnummern müssen und sollten Sie hier nicht in ein öffentliches Repository stellen.

**Comment by phschaer** [comment]
Ja, die Matrikelnummer habe ich wieder freigegeben. Bitte löschen Sie noch das Repository des Zweitaccounts für diesen Kurs. Ist ansonsten Datenmüll.
