### ISSUE TITLE
Problem opening notebooks 

### ISSUE THREAD

**Issue by floriflowers** [irgroup-classrooms/dis08-2021#60]
Hi everyone!
I am getting this error (see attached foto) when trying to open the Notebooks I downloaded from github.
I downloaded the file by clicking on raw, then save as and writing the .ipynb as the extension.
Also I am using a mac. 

Does anyone have an idea how i can fix this? Thank you!

![Screen Shot 2021-12-20 at 4 56 27 PM](https://user-images.githubusercontent.com/63049359/146796154-275d5646-5986-4c92-abdc-0f0c1774a610.png)

**Comment by phschaer** [comment]
Please don't "right-click" on the link to download the notebooks. This will only download an HTML representation.

You can 
1. clone the repository 
2. download the "raw" content on the GitHub representation of the notebook

**Comment by floriflowers** [comment]
Solved. 
For people who might have this issue too:
click raw -> cmd+s -> save as **page source** ( **not as webarchive** ) and delete any other extension other than .ipynb -> save - then it will work

**Comment by floriflowers** [comment]
> Please don't "right-click" on the link to download the notebooks. This will only download an HTML representation.
> 
> You can
> 
> 1. clone the repository
> 2. download the "raw" content on the GitHub representation of the notebook

Thank you, I will remember that too in the future!
